version: '3.8'

services:
  ecommerce-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/src/__pycache__
      - /app/src/generators/__pycache__
      - /app/src/utils/__pycache__
    env_file:
      - .env
    command: /bin/sh -c "while sleep 1000; do :; done" 